name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image with docker-compose
        run: |
          docker compose build --build-arg GEMINI_TOKEN=${{ secrets.GEMINI_TOKEN }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/dev-type ${{ secrets.DOCKER_USERNAME }}/dev-type:backend

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dev-type:backend
