name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image with docker-compose
        run: docker compose build

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dev-type:backend
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull image
        run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/dev-type:backend

      - name: Run container
        run: sudo docker run -d -p 8080:8080 -e GEMINI_TOKEN=${{ secrets.GEMINI_TOKEN }} --name back_end_dev_type ${{ secrets.DOCKER_HUB_USERNAME }}/dev-type:backend
